version: "3.9"

# Variables for mysql database
x-mysql-database: &MYSQL_DATABASE devdb
x-mysql-user: &MYSQL_USER devuser
x-mysql-password: &MYSQL_PASSWORD devdev

services:
  workspace:
    build:
      context: .
      dockerfile: ./docker/workspace/Dockerfile
    container_name: go-todo-sample-workspace
    tty: true
    volumes:
      - .:/go/src/github.com/mkaiho/go-todo-sample
    working_dir: /go/src/github.com/mkaiho/go-todo-sample
    ports:
      - 3000:3000
  mysqldb:
    build:
      context: ./docker/mysql
      dockerfile: ./Dockerfile
    container_name: go-todo-sample-db
    ports:
      - 13306:3306
    volumes:
      - ./docker/mysql/init.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: *MYSQL_DATABASE
      MYSQL_USER: *MYSQL_USER
      MYSQL_PASSWORD: *MYSQL_PASSWORD
