// Code generated by mockery v2.9.4. DO NOT EDIT.

package entity

import mock "github.com/stretchr/testify/mock"

// MockUser is an autogenerated mock type for the User type
type MockUser struct {
	mock.Mock
}

// Email provides a mock function with given fields:
func (_m *MockUser) Email() Email {
	ret := _m.Called()

	var r0 Email
	if rf, ok := ret.Get(0).(func() Email); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Email)
		}
	}

	return r0
}

// Name provides a mock function with given fields:
func (_m *MockUser) Name() UserName {
	ret := _m.Called()

	var r0 UserName
	if rf, ok := ret.Get(0).(func() UserName); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(UserName)
		}
	}

	return r0
}

// UserID provides a mock function with given fields:
func (_m *MockUser) UserID() UserID {
	ret := _m.Called()

	var r0 UserID
	if rf, ok := ret.Get(0).(func() UserID); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(UserID)
		}
	}

	return r0
}
