// Code generated by mockery v2.9.4. DO NOT EDIT.

package entity

import mock "github.com/stretchr/testify/mock"

// MockEmail is an autogenerated mock type for the Email type
type MockEmail struct {
	mock.Mock
}

// String provides a mock function with given fields:
func (_m *MockEmail) String() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Validate provides a mock function with given fields:
func (_m *MockEmail) Validate() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
