// Code generated by mockery v2.9.4. DO NOT EDIT.

package rdb

import (
	entity "github.com/mkaiho/go-todo-sample/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockIDGenerator is an autogenerated mock type for the IDGenerator type
type MockIDGenerator struct {
	mock.Mock
}

// GeneratID provides a mock function with given fields:
func (_m *MockIDGenerator) GeneratID() (entity.ID, error) {
	ret := _m.Called()

	var r0 entity.ID
	if rf, ok := ret.Get(0).(func() entity.ID); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(entity.ID)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
